# Site settings
title: GanYong Blog
SEOTitle: 甘永的博客 | GanYong Blog
header-img: img/post-bg-desk.jpg    #主页上面的图片
email: myganyong123@sina.com
description: "Every failure is leading towards success."
keyword: "GanYong, Change the World"
url: "GanYong123.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "欢迎来到德莱...额...我的博客~"
sidebar-avatar: /img/xiongbenxiong.jpg      # 你的头像



# SNS settings   你的社交链接
RSS: false
weibo_username:   懵懂的甘boy  
zhihu_username:   无风也要浪
# github_username:   
# jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]





# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: GanYong

# Gitalk
gitalk:
enable: true    #是否开启Gitalk评论
clientID: d6598db8fe476a4a322b                            #生成的clientID
clientSecret: a6340848931ff511e82a1a0ce0c890ede133c13d    #生成的clientSecret
repo: GanYong123.github.io    #仓库名称
owner: GanYong123    #github用户名
admin: GanYong123
distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: 
# 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends  友情链接
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/"
    },{
        title: "Github",
        herf: "https://github.com/"
    },{
        title: "Stackoverflow",
        herf: "https://stackoverflow.com/"
    }      
]

port: 4001
